language: node_js
notifications:
  email:
  - yiminghe@gmail.com
node_js:
- 0.1
before_script:
- node server &
- npm install gulp bower mocha-phantomjs -g
- bower install
- phantomjs --version
script:
- npm test
- mocha-phantomjs http://localhost:8002/tests/runner.html
- mocha-phantomjs http://localhost:8002/tests/runner.html?build
- mocha-phantomjs -R node_modules/node-jscover/lib/reporters/mocha/console http://localhost:8002/tests/runner.html?coverage