language: node_js
notifications:
  email:
  - yiminghe@gmail.com
node_js:
- 0.11
before_script:
- npm start &
- npm install mocha-phantomjs -g
script:
- npm test
- npm run browser-test
- npm run browser-test-cover
- npm run saucelabs
env:
  global:
  - secure: TV0dySOJgCsNZPo2qAeHn71wfl0ALwTRl092BshYDJxhlgPVs5eZ7kJalEe86IxNdaJZnGUNr0S0ONvPtoYjgopvlO6hffjnKCXSSXhLh0+RG45lUrHXCvQRUgvuIhluChHKNXXqy3Ml54BsEj2L6P60OLbzk7Ts8U6Sqwf+unk=
  - secure: n0M6AAUj25xVwZfUixcaWf8By4RTc15+aq8MHkvlnrgV/ce9eJdqkAMKKrI8aHsK7RJ1z8OH2ohZZRhK53XyH9avZquRjWhaxwdgQVFxUPCxUG+4Nyks9DUCfsR2UJZbHw0llitiY5Zrz9gd7ZKr/v7nn40RLVryayjYcqpzLlw=
